# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.


---
conf.py:
  copyright: 2024
  project: Automatically generates FAL metadata for files by means of public LLMs
  version: 0.1-beta
  release: 0.1.0
  latex_documents:
  - - Index
    - my-ext.tex
    - 'Automatically generates FAL metadata for files by means of public LLMs'
    - Christian Spoo
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
  intersphinx_mapping:
    t3api:
    - http://docs.typo3.org/typo3cms/CoreApiReference/
    - null
    t3tsref:
    - http://docs.typo3.org/typo3cms/TyposcriptReference/
    - null
    t3start:
    - http://docs.typo3.org/typo3cms/GettingStartedTutorial/
    - null
    t3editors:
    - http://docs.typo3.org/typo3cms/EditorsTutorial/
    - null
...
